server.port: 8081

spring:
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false

  datasource:
    url: jdbc:h2:mem:oauth10a-server;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        show_sql: true
        use_sql_comments: true
        format_sql: true
